import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TaxSavy",
  description: "Generated by Atharv Naik ",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" > 
    <meta name="google-site-verification" content="P4AVPBfjd0Tk8QQg_nm5Id-FEawMfaX1xsM5ZoCX5JI" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
